# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "AMAlbala's blog"

author:
  
  twitter:          am_albala
  github:           amalbala
  linkedin:         antoniomartinezalbala
  medium:           amalbala
  aboutme:          amalbala
  email:            amalbala@gmail.com

copyright:
  year:             2017
  name:             AMAlbala

# Google-analytics
google-analytics:
  id:               "UA-93990221-1"

# Disqus
disqus:
  id:               "amalbala"

# URL
url:                "https://amalbala.github.io" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Europe/Madrid
permalink:          /:day-:month-:year/:title/

# Pagination
paginate:          5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "https://about.me/amalbala"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/amalbala"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]